#!/usr/bin/env node

/**
 * Octavius Setup Script
 *
 * Automates first-run configuration:
 * 1. Creates .env.local with a generated API secret
 * 2. Ensures .data/ directory exists for SQLite
 * 3. Detects OpenClaw gateway
 * 4. Runs npm install if needed
 * 5. Prints next steps
 */

import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '')

console.log('\n🧠 Octavius — Setup\n')

// Step 1: Generate .env.local
const envPath = join(ROOT, '.env.local')
if (existsSync(envPath)) {
  console.log('✓ .env.local already exists — skipping')
} else {
  const secret = randomBytes(32).toString('hex')
  const envContent = [
    '# Generated by: npm run setup',
    `# Created: ${new Date().toISOString()}`,
    '',
    '# Memory Service API secret token',
    '# Leave empty or remove this line to allow unauthenticated local access (recommended for self-hosted)',
    '# Set a value to require Bearer auth on all /api/memory/* endpoints',
    `# OCTAVIUS_API_SECRET=${secret}`,
    '',
    '# OpenClaw gateway address (auto-detected)',
    'OPENCLAW_GATEWAY_HOST=localhost',
    'OPENCLAW_GATEWAY_PORT=18789',
    '',
    '# Base directory for agent workspace files',
    '# OPENCLAW_HOME=~/.openclaw',
    '',
  ].join('\n')

  writeFileSync(envPath, envContent, 'utf-8')
  console.log('✓ Created .env.local (auth disabled for local use — edit to enable)')
}

// Step 2: Ensure .data directory for SQLite
const dataDir = join(ROOT, '.data')
if (!existsSync(dataDir)) {
  mkdirSync(dataDir, { recursive: true })
  console.log('✓ Created .data/ directory for SQLite database')
} else {
  console.log('✓ .data/ directory exists')
}

// Step 3: Check node_modules
const nodeModules = join(ROOT, 'node_modules')
if (!existsSync(nodeModules)) {
  console.log('⏳ Installing dependencies...')
  try {
    execSync('npm install', { cwd: ROOT, stdio: 'inherit' })
    console.log('✓ Dependencies installed')
  } catch {
    console.error('✗ npm install failed — please run it manually')
  }
} else {
  console.log('✓ Dependencies already installed')
}

// Step 4: Detect OpenClaw gateway
let gatewayFound = false
try {
  const net = await import('node:net')
  gatewayFound = await new Promise((resolve) => {
    const socket = new net.default.Socket()
    socket.setTimeout(2000)
    socket.on('connect', () => {
      socket.destroy()
      resolve(true)
    })
    socket.on('timeout', () => {
      socket.destroy()
      resolve(false)
    })
    socket.on('error', () => {
      resolve(false)
    })
    socket.connect(18789, 'localhost')
  })
} catch {
  gatewayFound = false
}

if (gatewayFound) {
  console.log('✓ OpenClaw gateway detected on localhost:18789')
} else {
  console.log('○ No OpenClaw gateway detected on localhost:18789 (optional)')
}

// Step 5: Check for OpenClaw config
const openclawConfigPaths = [
  join(process.env.HOME ?? '', '.openclaw', 'openclaw.json'),
  join(process.env.OPENCLAW_HOME ?? '', 'openclaw.json'),
]

let openclawConfigFound = false
for (const p of openclawConfigPaths) {
  if (p && existsSync(p)) {
    openclawConfigFound = true
    console.log(`✓ OpenClaw config found at ${p}`)
    break
  }
}
if (!openclawConfigFound) {
  console.log('○ No OpenClaw config found (agents will work without gateway)')
}

// Summary
console.log('\n' + '─'.repeat(50))
console.log('\n✅ Setup complete! Next steps:\n')
console.log('  1. Start the dashboard:')
console.log('     npm run dev\n')
console.log('  2. Open http://localhost:3000\n')
console.log('  3. Go to Settings → fill in your profile\n')

if (gatewayFound) {
  console.log('  4. Go to Settings → Gateway Connection')
  console.log('     Gateway detected — click "Connect" to link agents\n')
} else {
  console.log('  4. (Optional) Install OpenClaw for AI agents:')
  console.log('     npm i -g openclaw && openclaw gateway run\n')
}

console.log('📖 Full docs: https://github.com/wabecerra/octavius#readme\n')
