#!/usr/bin/env node

/**
 * Octavius Setup Script
 *
 * Automates first-run configuration:
 * 1. Creates .env.local with a generated API secret
 * 2. Ensures .data/ directory exists for SQLite
 * 3. Detects OpenClaw gateway
 * 4. Runs npm install if needed
 * 5. Prints next steps
 */

import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { execSync } from 'node:child_process'

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '')

console.log('\n🧠 Octavius — Setup\n')

// Step 0: Pre-flight checks
const nodeVersion = process.versions.node.split('.').map(Number)
if (nodeVersion[0] < 22) {
  console.error(`✗ Node.js 22+ required (you have ${process.version})`)
  console.error('  Install via: https://nodejs.org/ or nvm install 22')
  process.exit(1)
}
console.log(`✓ Node.js ${process.version}`)

// Check if port 3000 is available
try {
  const net = await import('node:net')
  const portFree = await new Promise((resolve) => {
    const server = net.default.createServer()
    server.once('error', (err) => {
      resolve(err.code !== 'EADDRINUSE')
    })
    server.once('listening', () => {
      server.close()
      resolve(true)
    })
    server.listen(3000, '0.0.0.0')
  })
  if (!portFree) {
    console.log('⚠ Port 3000 is in use — you may need to stop the other process or use a different port:')
    console.log('  npm run dev -- -p 3001')
    console.log('  Or kill the existing process: lsof -ti:3000 | xargs kill')
  } else {
    console.log('✓ Port 3000 is available')
  }
} catch {
  // Non-fatal — just skip the check
}

// Step 1: Generate .env.local
const envPath = join(ROOT, '.env.local')
if (existsSync(envPath)) {
  console.log('✓ .env.local already exists — skipping')
} else {
  const secret = randomBytes(32).toString('hex')
  const envContent = [
    '# Generated by: npm run setup',
    `# Created: ${new Date().toISOString()}`,
    '',
    '# Memory Service API secret token',
    '# Leave empty or remove this line to allow unauthenticated local access (recommended for self-hosted)',
    '# Set a value to require Bearer auth on all /api/memory/* endpoints',
    `# OCTAVIUS_API_SECRET=${secret}`,
    '',
    '# OpenClaw gateway address (auto-detected)',
    'OPENCLAW_GATEWAY_HOST=localhost',
    'OPENCLAW_GATEWAY_PORT=18789',
    '',
    '# Base directory for agent workspace files',
    '# OPENCLAW_HOME=~/.openclaw',
    '',
  ].join('\n')

  writeFileSync(envPath, envContent, 'utf-8')
  console.log('✓ Created .env.local (auth disabled for local use — edit to enable)')
}

// Step 2: Ensure .data directory for SQLite
const dataDir = join(ROOT, '.data')
if (!existsSync(dataDir)) {
  mkdirSync(dataDir, { recursive: true })
  console.log('✓ Created .data/ directory for SQLite database')
} else {
  console.log('✓ .data/ directory exists')
}

// Step 3: Install dependencies
const nodeModules = join(ROOT, 'node_modules')
const needsInstall = !existsSync(nodeModules) || !existsSync(join(nodeModules, '.package-lock.json'))
if (needsInstall) {
  console.log('⏳ Installing dependencies...')
  try {
    execSync('npm install --include=dev', { cwd: ROOT, stdio: 'inherit' })
    console.log('✓ Dependencies installed')
  } catch {
    // Retry with legacy peer deps (Node 24+ sometimes has resolution issues)
    console.log('⏳ Retrying with --legacy-peer-deps...')
    try {
      execSync('npm install --include=dev --legacy-peer-deps', { cwd: ROOT, stdio: 'inherit' })
      console.log('✓ Dependencies installed (with --legacy-peer-deps)')
    } catch {
      console.error('✗ npm install failed — check errors above')
      process.exit(1)
    }
  }
} else {
  console.log('✓ Dependencies already installed')
}

// Step 3b: Verify better-sqlite3 native module loads
try {
  const { createRequire } = await import('node:module')
  const require = createRequire(join(ROOT, 'package.json'))
  require('better-sqlite3')
  console.log('✓ better-sqlite3 native module OK')
} catch (err) {
  console.error('✗ better-sqlite3 failed to load — native compilation issue')
  console.error(`  Error: ${err.message}`)
  if (process.platform === 'linux') {
    console.error('  You may need build tools: sudo apt-get install -y python3 make g++')
    console.error('  Or on Amazon Linux:      sudo yum install -y python3 make gcc-c++')
  } else if (process.platform === 'darwin') {
    console.error('  You may need: xcode-select --install')
  }
  console.error('  After installing build tools, delete node_modules and re-run: npm run setup')
  process.exit(1)
}

// Step 4: Detect OpenClaw gateway
let gatewayFound = false
try {
  const net = await import('node:net')
  gatewayFound = await new Promise((resolve) => {
    const socket = new net.default.Socket()
    socket.setTimeout(2000)
    socket.on('connect', () => {
      socket.destroy()
      resolve(true)
    })
    socket.on('timeout', () => {
      socket.destroy()
      resolve(false)
    })
    socket.on('error', () => {
      resolve(false)
    })
    socket.connect(18789, 'localhost')
  })
} catch {
  gatewayFound = false
}

if (gatewayFound) {
  console.log('✓ OpenClaw gateway detected on localhost:18789')
} else {
  console.log('○ No OpenClaw gateway detected on localhost:18789 (optional)')
}

// Step 4b: Check/install lossless-claw plugin
let lcmInstalled = false
if (gatewayFound) {
  try {
    const { stdout } = execSync('openclaw plugins list --json 2>/dev/null', { encoding: 'utf8' })
    lcmInstalled = stdout.includes('lossless-claw')
  } catch {
    // plugins list not available or failed
  }

  if (lcmInstalled) {
    console.log('✓ lossless-claw plugin already installed')
  } else {
    console.log('⏳ Installing lossless-claw (persistent conversation memory)...')
    try {
      execSync('openclaw plugins install @martian-engineering/lossless-claw', { cwd: ROOT, stdio: 'inherit' })
      lcmInstalled = true
      console.log('✓ lossless-claw installed — agents will never lose conversation context')
    } catch {
      console.log('○ Could not auto-install lossless-claw — install manually:')
      console.log('  openclaw plugins install @martian-engineering/lossless-claw')
    }
  }
} else {
  console.log('○ Skipping lossless-claw install (no gateway detected)')
}

// Step 5: Check for OpenClaw config
const openclawConfigPaths = [
  join(process.env.HOME ?? '', '.openclaw', 'openclaw.json'),
  join(process.env.OPENCLAW_HOME ?? '', 'openclaw.json'),
]

let openclawConfigFound = false
for (const p of openclawConfigPaths) {
  if (p && existsSync(p)) {
    openclawConfigFound = true
    console.log(`✓ OpenClaw config found at ${p}`)
    break
  }
}
if (!openclawConfigFound) {
  console.log('○ No OpenClaw config found (agents will work without gateway)')
}

// Step 6: Validate PostCSS config
const postcssPath = join(ROOT, 'postcss.config.mjs')
const postcssCjsPath = join(ROOT, 'postcss.config.js')
if (existsSync(postcssPath) || existsSync(postcssCjsPath)) {
  const configFile = existsSync(postcssPath) ? postcssPath : postcssCjsPath
  const content = readFileSync(configFile, 'utf-8')
  if (!content.includes('tailwindcss')) {
    console.log('⚠ PostCSS config exists but missing tailwindcss plugin')
  } else {
    console.log(`✓ PostCSS config OK (${existsSync(postcssPath) ? 'ESM' : 'CJS'})`)
  }
  if (!content.includes('autoprefixer')) {
    console.log('○ Tip: autoprefixer not found in PostCSS config (optional but recommended)')
  }
} else {
  console.log('⚠ No PostCSS config found — Tailwind CSS may not work')
  console.log('  Run: npm run doctor for diagnostics')
}

// Summary
console.log('\n' + '─'.repeat(50))
console.log('\n✅ Setup complete! Next steps:\n')
console.log('  1. Start the dashboard:')
console.log('     npm run dev\n')
console.log('  2. Open http://localhost:3000\n')
console.log('  3. Go to Settings → fill in your profile\n')

if (gatewayFound) {
  console.log('  4. Go to Settings → Gateway Connection')
  console.log('     Gateway detected — click "Connect" to link agents')
  if (lcmInstalled) {
    console.log('     ✓ lossless-claw active — conversation memory is persistent\n')
  } else {
    console.log('     ○ Run: openclaw plugins install @martian-engineering/lossless-claw')
    console.log('       for persistent conversation memory\n')
  }
} else {
  console.log('  4. (Optional) Install OpenClaw for AI agents:')
  console.log('     npm i -g openclaw && openclaw gateway run')
  console.log('     Then: openclaw plugins install @martian-engineering/lossless-claw\n')
}

console.log('📖 Full docs: https://github.com/wabecerra/octavius#readme\n')
